name: React CI

on:
  push:
    paths:
      - '/react/e-library/**'
  pull_request:
    paths:
      - '/react/e-library/**'
  workflow_run:
    workflows: ["E-Library-Management-System"]
    types:
      - requested

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        cd ./react/e-library
        npm install
    - name: Run tests
      run: | 
        cd ./react/e-library
        npm test   