name: Spring CI

on:
  push:
    paths:
      - '/spring/**'
  pull_request:
    paths:
      - '/spring/**'
  workflow_run:
    workflows: ["E-Library-Management-System"]
    types:
      - requested

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '19'
    # - name: Set up Maven
    #   uses: s4u/setup-maven-action@< version >

    - name: Build Spring project
      run: |
        cd ./spring
        ./mvnw.sh clean install

    - name: Run Spring tests
      run: |
        cd ./spring_app
        ./mvnw.sh test