name: E-Library-Management-System

on:
  push:
  
jobs:
  spring_workflow:
    runs-on: ubuntu-latest
    name: Spring Workflow

    steps:
    - name: Trigger Spring Workflow
      uses: actions/workflow-dispatch@v2
      with:
        workflow: Spring CI
        ref: main
        